import type { Metadata } from "next";
import { Inter, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { TokenCreationFormProvider } from "@/components/providers/token-creation-form";
import { SolanaClientProvider } from "@/components/providers/solana-client";
import {
  PrivyConfigProvider,
  PrivyAsSolanaWalletProvider,
} from "@/components/providers/privy-as-solana-wallet";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/sonner";

const poppinsSans = Poppins({
  variable: "--font-poppins-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppinsSans.className}  ${geistMono.variable} antialiased`}
      >
        <SolanaClientProvider>
          <PrivyConfigProvider appId="cmjuf6ftn021ml50cszzykcsu">
            <PrivyAsSolanaWalletProvider>
              <TokenCreationFormProvider>
                <TooltipProvider>
                  <Navbar />
                  {children}
                </TooltipProvider>
              </TokenCreationFormProvider>
            </PrivyAsSolanaWalletProvider>
          </PrivyConfigProvider>
        </SolanaClientProvider>
        <Toaster expand duration={3600000} />
      </body>
    </html>
  );
}
